// libs/star-setup/src/components/WAN/VPNClient/components/Switch.tsx
import { component$, type QRL } from "@builder.io/qwik";

export interface SwitchProps {
  id: string;
  label: string;
  checked: boolean;
  onChange$: QRL<(checked: boolean) => void>;
  disabled?: boolean;
}

export const Switch = component$<SwitchProps>(
  ({ id, label, checked, onChange$, disabled = false }) => {
    return (
      <div class="flex items-center">
        <label
          for={id}
          class="relative inline-flex cursor-pointer items-center"
        >
          <input
            type="checkbox"
            id={id}
            class="peer sr-only"
            checked={checked}
            disabled={disabled}
            onChange$={(_, target) => onChange$(target.checked)}
          />
          <div
            class="peer h-6 w-11 rounded-full bg-gray-200 after:absolute after:left-[2px] after:top-[2px]
                    after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white
                    after:transition-all after:content-[''] peer-checked:bg-primary-500
                    peer-checked:after:translate-x-full peer-checked:after:border-white
                    peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-primary-500
                    peer-disabled:cursor-not-allowed peer-disabled:opacity-60
                    dark:bg-gray-700 dark:after:border-gray-600"
          ></div>
          <span class="text-text-default ml-3 text-sm font-medium dark:text-text-dark-default">
            {label}
          </span>
        </label>
      </div>
    );
  },
);

// libs/ui/primitives/src/switch/switch.tsx
import * as React from 'react';
import * as SwitchPrimitives from '@radix-ui/react-switch';

import { cn } from '../lib/utils';

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
  <SwitchPrimitives.Root
    className={cn(
      'peer inline-flex h-7 w-12 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent shadow-sm transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-green-500 data-[state=unchecked]:bg-slate-300 dark:data-[state=unchecked]:bg-slate-600',
      className
    )}
    {...props}
    ref={ref}
  >
    <SwitchPrimitives.Thumb
      className={cn(
        'pointer-events-none block h-5 w-5 rounded-full bg-white shadow-lg ring-0 transition-transform duration-200 data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-1'
      )}
    />
  </SwitchPrimitives.Root>
));
Switch.displayName = SwitchPrimitives.Root.displayName;

export { Switch };
